services:
  - type: web
    name: axivibe
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: unsafe-none
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: unsafe-none
